FROM ccr.ccs.tencentyun.com/chico/funasr-server:latest

WORKDIR /app

# 复制必要文件
COPY model_batch.py ./
COPY server_batch.py ./
COPY requirements.txt ./

# 修改缓存路径
ENV MODEL_PATH="FunAudioLLM/Fun-ASR-MLT-Nano-2512" \
    DEVICE="cuda:0" \
    BATCH_SIZE="6" \
    MAX_BATCH_SIZE="10"

# 暴露端口
EXPOSE 8000

# 启动服务
CMD ["python", "server_batch.py", "--host", "0.0.0.0", "--port", "8000"]
